apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: j8pz2ajzr-go-gitops
  description: This is GitOps manifest for j8pz2ajzr-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=j8pz2ajzr-go
    backstage.io/kubernetes-id: j8pz2ajzr-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: j8pz2ajzr-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:j8pz2ajzr-go
